### ISSUE TITLE
Enum problem with latest version

### ISSUE THREAD

**Issue by yeagerm** [openaps/openomni#44]
First, need to add `pip install enum` to instructions.
enum.EnumBadKeyError: Enumeration keys must be strings: 5

--

(omnipod) compost:bin yeagerm$ omni_listen_rfcat
Traceback (most recent call last):
  File "/Users/yeagerm/anaconda/envs/omnipod/bin/omni_listen_rfcat", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/yeagerm/openomni/openomni/bin/omni_listen_rfcat", line 60, in <module>
    main()
  File "/Users/yeagerm/openomni/openomni/bin/omni_listen_rfcat", line 41, in main
    packet = Packet(data)
  File "/Users/yeagerm/openomni/openomni/packet.py", line 50, in __init__
    self.packet_type = PacketType(byte5 >> 5)
  File "/Users/yeagerm/anaconda/envs/omnipod/lib/python2.7/site-packages/enum.py", line 199, in __init__
    raise EnumBadKeyError(key)
enum.EnumBadKeyError: Enumeration keys must be strings: 5

**Comment by panctronic** [comment]
Was that a spurious failure, or repeatable? I've seen enum parse failures with random radio noise.

Did you install with requirements.txt, or setup.py? requirements.txt has already been updated to show the enum dependency. I'll take the doc update.

**Comment by panctronic** [comment]
Aha, the problem actually is the same as https://github.com/FreeOpcUa/python-opcua/issues/50  -- the wrong enum package was installed. Instead of pip install enum, you wanted pip install enum34

**Comment by yeagerm** [comment]
Yes enum34 makes it work. Solved
